{{/*
expand the name of the chart.
*/}}
{{- define "feed.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
create a default fully qualified app name.
*/}}
{{- define "feed.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
create chart name and version as used by the chart label.
*/}}
{{- define "feed.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
common labels
*/}}
{{- define "feed.labels" -}}
helm.sh/chart: {{ include "feed.chart" . }}
{{ include "feed.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
selector labels
*/}}
{{- define "feed.selectorLabels" -}}
app.kubernetes.io/name: {{ include "feed.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
create the name of the service account to use
*/}}
{{- define "feed.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "feed.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
cnpg cluster name
*/}}
{{- define "feed.cnpg.name" -}}
{{- if .Values.cnpg.nameOverride }}
{{- .Values.cnpg.nameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-db" (include "feed.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{/*
cnpg secret name (auto-generated by cnpg operator)
*/}}
{{- define "feed.cnpg.secretName" -}}
{{- printf "%s-app" (include "feed.cnpg.name" .) }}
{{- end }}
