{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "feed.cnpg.name" . }}-backup
  labels:
    {{- include "feed.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cnpg.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ include "feed.cnpg.name" . }}
{{- end }}
