{{- if and (eq .Values.database.driver "sqlite") .Values.database.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "feed.fullname" . }}-data
  labels:
    {{- include "feed.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.database.sqlite.persistence.accessModes | nindent 4 }}
  {{- if .Values.database.sqlite.persistence.storageClass }}
  storageClassName: {{ .Values.database.sqlite.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.sqlite.persistence.size }}
{{- end }}
