{{/*
expand the name of the chart.
*/}}
{{- define "konfig.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
create a default fully qualified app name.
*/}}
{{- define "konfig.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
name of one component's resources, e.g. konfig-controlplane.
*/}}
{{- define "konfig.componentName" -}}
{{- printf "%s-%s" (include "konfig.fullname" .ctx) .component | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
create chart name and version as used by the chart label.
*/}}
{{- define "konfig.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
common labels. takes a dict of ctx and component.
*/}}
{{- define "konfig.labels" -}}
helm.sh/chart: {{ include "konfig.chart" .ctx }}
{{ include "konfig.selectorLabels" . }}
{{- if .ctx.Chart.AppVersion }}
app.kubernetes.io/version: {{ .ctx.Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/part-of: konfig
app.kubernetes.io/managed-by: {{ .ctx.Release.Service }}
{{- end }}

{{/*
selector labels. takes a dict of ctx and component.
*/}}
{{- define "konfig.selectorLabels" -}}
app.kubernetes.io/name: {{ include "konfig.name" .ctx }}
app.kubernetes.io/instance: {{ .ctx.Release.Name }}
{{- if .component }}
app.kubernetes.io/component: {{ .component }}
{{- end }}
{{- end }}

{{/*
create the name of the service account to use
*/}}
{{- define "konfig.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "konfig.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
image reference for a component. takes a dict of ctx and image.
*/}}
{{- define "konfig.image" -}}
{{- printf "%s:%s" .image.repository (.image.tag | default .ctx.Chart.AppVersion) }}
{{- end }}

{{/*
name of the secret the controlplane reads its credentials from.
*/}}
{{- define "konfig.controlplane.secretName" -}}
{{- if .Values.controlplane.existingSecret }}
{{- .Values.controlplane.existingSecret }}
{{- else }}
{{- include "konfig.componentName" (dict "ctx" . "component" "controlplane") }}
{{- end }}
{{- end }}

{{/*
cnpg cluster name
*/}}
{{- define "konfig.cnpg.name" -}}
{{- if .Values.cnpg.nameOverride }}
{{- .Values.cnpg.nameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-db" (include "konfig.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{/*
cnpg application secret, generated by the operator. it carries the full
connection string under `uri`, which is what the controlplane wants: building
one from the parts would have to url-encode a password this chart never sees.
*/}}
{{- define "konfig.cnpg.secretName" -}}
{{- printf "%s-app" (include "konfig.cnpg.name" .) }}
{{- end }}

{{/*
name of the secret holding the message bus passwords.
*/}}
{{- define "konfig.messagebus.secretName" -}}
{{- default .Values.messagebus.auth.secretName .Values.messagebus.auth.existingSecret }}
{{- end }}

{{/*
service name of the bundled nats release, mirroring the nats chart's own
fullname template so the controlplane can dial it.
*/}}
{{- define "konfig.nats.fullname" -}}
{{- $nats := .Values.nats | default dict }}
{{- if $nats.fullnameOverride }}
{{- $nats.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default "nats" $nats.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
the nats url the controlplane dials. when the bus is bundled, the password is
interpolated by kubernetes from the environment variable defined before it on
the container, so it never lands in a configmap.
*/}}
{{- define "konfig.messagebus.url" -}}
{{- if .Values.nats.enabled }}
{{- printf "nats://controlplane:$(NATS_CONTROLPLANE_PASSWORD)@%s:4222" (include "konfig.nats.fullname" .) }}
{{- else }}
{{- .Values.messagebus.url }}
{{- end }}
{{- end }}

{{/*
the first hostname an ingress or httproute publishes for a component, with its
scheme. takes a dict of ctx and values (the component's values).
*/}}
{{- define "konfig.componentURL" -}}
{{- $values := .values }}
{{- if $values.ingress.enabled }}
{{- $host := (first $values.ingress.hosts).host }}
{{- $scheme := "http" }}
{{- range $values.ingress.tls }}
{{- if has $host .hosts }}
{{- $scheme = "https" }}
{{- end }}
{{- end }}
{{- printf "%s://%s" $scheme $host }}
{{- else if $values.httpRoute.enabled }}
{{- printf "http://%s" (first $values.httpRoute.hostnames) }}
{{- end }}
{{- end }}

{{/*
browser-facing url of the console. the fallback is what `kubectl port-forward`
gives you, so a deployment with no ingress still works from a laptop.
*/}}
{{- define "konfig.consoleURL" -}}
{{- if .Values.urls.console }}
{{- .Values.urls.console | trimSuffix "/" }}
{{- else }}
{{- $derived := include "konfig.componentURL" (dict "ctx" . "values" .Values.console) }}
{{- $derived | default (printf "http://localhost:%d" (int .Values.console.service.port)) }}
{{- end }}
{{- end }}

{{/*
browser-facing url of the controlplane api.
*/}}
{{- define "konfig.apiURL" -}}
{{- if .Values.urls.api }}
{{- .Values.urls.api | trimSuffix "/" }}
{{- else }}
{{- $derived := include "konfig.componentURL" (dict "ctx" . "values" .Values.controlplane) }}
{{- $derived | default (printf "http://localhost:%d" (int .Values.controlplane.service.port)) }}
{{- end }}
{{- end }}

{{/*
refuse a configuration that cannot work, here rather than as a crashloop an
operator has to read logs to explain. included from every template that would
otherwise render something incomplete.
*/}}
{{- define "konfig.validate" -}}
{{- if not (or .Values.cnpg.enabled .Values.database.url .Values.database.existingSecret) }}
{{- fail "konfig: no database. set cnpg.enabled=true, database.url, or database.existingSecret - the controlplane refuses to start without postgres." }}
{{- end }}
{{- if and .Values.cnpg.enabled (or .Values.database.url .Values.database.existingSecret) }}
{{- fail "konfig: two databases configured. cnpg.enabled is on and database.url/database.existingSecret is also set; pick one." }}
{{- end }}
{{- if not .Values.controlplane.existingSecret }}
{{- if not .Values.controlplane.auth.jwtSigningToken }}
{{- fail "konfig: controlplane.auth.jwtSigningToken is empty. the controlplane refuses to start without it, because an empty signing key verifies any session token an attacker signs with it. generate one with: openssl rand -hex 32" }}
{{- end }}
{{- if and .Values.controlplane.auth.basicAuth.enabled (not .Values.controlplane.auth.basicAuth.password) }}
{{- fail "konfig: controlplane.auth.basicAuth.enabled is true but no password is set. set controlplane.auth.basicAuth.password, or disable basic auth and sign in with github." }}
{{- end }}
{{- if and .Values.controlplane.auth.github.enabled (not (and .Values.controlplane.auth.github.clientId .Values.controlplane.auth.github.clientSecret)) }}
{{- fail "konfig: controlplane.auth.github.enabled is true but clientId or clientSecret is empty." }}
{{- end }}
{{- if and (not .Values.controlplane.auth.basicAuth.enabled) (not .Values.controlplane.auth.github.enabled) }}
{{- fail "konfig: no way to sign in. enable controlplane.auth.basicAuth or controlplane.auth.github." }}
{{- end }}
{{- if .Values.controlplane.masterKey }}
{{- if ne (len (b64dec .Values.controlplane.masterKey)) 32 }}
{{- fail "konfig: controlplane.masterKey must be base64 that decodes to 32 bytes. generate one with: openssl rand -base64 32" }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.nats.enabled }}
{{- if not .Values.messagebus.auth.existingSecret }}
{{- if not (and .Values.messagebus.auth.controlplanePassword .Values.messagebus.auth.agentPassword) }}
{{- fail "konfig: the bundled nats needs credentials. set messagebus.auth.controlplanePassword and messagebus.auth.agentPassword (or messagebus.auth.existingSecret), or point messagebus.url at a bus you already run with nats.enabled=false." }}
{{- end }}
{{- end }}
{{- $referenced := ((((.Values.nats.container).env).NATS_CONTROLPLANE_PASSWORD).valueFrom.secretKeyRef).name }}
{{- if ne $referenced (include "konfig.messagebus.secretName" .) }}
{{- fail (printf "konfig: the nats subchart reads its passwords from the secret %q but this chart manages %q. helm cannot template a subchart's values, so both nats.container.env entries have to name the secret this chart uses - messagebus.auth.existingSecret when you bring your own, messagebus.auth.secretName when the chart creates it." $referenced (include "konfig.messagebus.secretName" .)) }}
{{- end }}
{{- else if not .Values.messagebus.url }}
{{- fail "konfig: nats.enabled is false and messagebus.url is empty. the controlplane has no bus to dial." }}
{{- end }}
{{- end }}

{{/*
name of the secret holding the database connection string. the chart manages one
only when `database.url` is set in values; cnpg deployments read the operator's
own secret instead.
*/}}
{{- define "konfig.database.secretName" -}}
{{- if .Values.database.existingSecret }}
{{- .Values.database.existingSecret }}
{{- else }}
{{- printf "%s-database" (include "konfig.componentName" (dict "ctx" . "component" "controlplane")) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
