{{- if not .Values.controlplane.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "konfig.controlplane.secretName" . }}
  labels:
    {{- include "konfig.labels" (dict "ctx" . "component" "controlplane") | nindent 4 }}
type: Opaque
stringData:
  JWT_SIGNING_TOKEN: {{ .Values.controlplane.auth.jwtSigningToken | quote }}
  {{- if .Values.controlplane.auth.basicAuth.enabled }}
  BASIC_AUTH_USER: {{ .Values.controlplane.auth.basicAuth.username | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.controlplane.auth.basicAuth.password | quote }}
  {{- end }}
  {{- if .Values.controlplane.auth.github.enabled }}
  GITHUB_CLIENT_ID: {{ .Values.controlplane.auth.github.clientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.controlplane.auth.github.clientSecret | quote }}
  {{- end }}
  {{- with .Values.controlplane.githubApp.appId }}
  GITHUB_APP_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.controlplane.githubApp.privateKey }}
  GITHUB_APP_PRIVATE_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.controlplane.agents.enrolmentToken }}
  AGENT_ENROLMENT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.controlplane.agents.token }}
  AGENT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.controlplane.masterKey }}
  KONFIG_MASTER_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
