{{- if and (not .Values.cnpg.enabled) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "konfig.database.secretName" . }}
  labels:
    {{- include "konfig.labels" (dict "ctx" . "component" "controlplane") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}
